### ISSUE TITLE
Make the protobuf definitions into a directory that reflects the package name.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#145]
It's common to store protocol buffers in a proto/ directory structure. The current location api/protobuf-spec is problematic because of the dash and the inconsistent naming because some languages use the directory as the namespace.

**Comment by joeholley** [comment]
That directory is only supposed to be the `proto` files. Since they have to be compiled into language-specific libraries/modules, those are the files that need to be in a directory that is easy to import - in fact, in golang, we discussed wanting them in the `pkg/` directory so they are `go get`-able. Nothing can directly import the `proto` files anyway and I don't think we want them in the directory that gets included in builds? The intent of where they are now was to have the these in language-agnostic directory to serve as the human-readable API spec.  The question of where `protoc`-compiled libraries/modules for languages outside of golang should live is probably worth answering in a standard way, though.  I'm not sure if there's a accepted way to do that, to be honest?  The approach we've taken so far is 'they don't have a specific home in this repo' and they just live in the directories of the code examples that use them.

**Comment by jeremyje** [comment]
protos/*.proto is a common directory for protobufs. Or something that would have reasonable namespacing like, openmatch/api/*.proto. PHP appears to namespace based on the directory.

**Comment by joeholley** [comment]
Okay.  Whatever you guys think is best.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/157 did half the work here.

**Comment by jeremyje** [comment]
We are having a problem where rapid protobuf changes are breaking clients because there's lack of test coverage. At this point I think a few of the following things will inevitably occur.
 * Certain examples will be rewritten to not have a hard dependency on the database and part of that rewrite is to rely on the public facing protos.
 * The new clients will have tests that guarantee that they work properly as things change.
 * Older examples will either rot and will have to be revived once someone takes interest to them.

**Comment by jeremyje** [comment]
This is done.
