### ISSUE TITLE
Add make presubmit to keep auto generated files in sync.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#226]
Right now it's very adhoc when the auto-generated files that are checked in get updated. We can add a make presubmit that force updates all the files before they are checked in.

**Comment by Laremere** [comment]
From discussion with Jeremy:

He's fixing protos now, but will let the install yaml drift.  

If the yaml files change in incompatible ways, then the install would break.  

It's not possible to have the the install yaml files reference the current build because they would need to include

**Comment by Laremere** [comment]
From discussion with Jeremy:

He's fixing protos now, but will let the install yaml drift for the moment.

If the yaml files change in a way which is incompatible with the referenced versioned image, then the install would break.  It's not good to have things be broken all the time.
It's not possible to have the the install yaml files reference the current build because they would need to reference the commit hash which includes a hash of itself.  Plus we don't want that file to change every single commit.

Jeremy proposed having the install/yaml reference a recent unstable build, but then things will still break on head for short periods of time, and checking out an old commit will be broken often.

I propose that we remove support for using the install yaml files on the development branch.  They are the easiest way to do things, so we want to continue having them for the release.  We can consider releasing them as release artifacts (like you would with a binary on github).  However I think they should be removed from the git repository.
