### ISSUE TITLE
Fix Promethus k8s resource ordering issue

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#46]
In the part of the dev guide that covers [applying the kubernetes configs for the prometheus operator](https://github.com/GoogleCloudPlatform/open-match/blob/020rc2/docs/development.md#running-open-match-in-a-development-environment), it has:

```
kubectl apply -f prometheus_operator.json
kubectl apply -f prometheus.json
kubectl apply -f prometheus_service.json
kubectl apply -f metrics_servicemonitor.json
```

A couple users have noticed errors creating these services that go away on applying them a second time.  There's probably a resource that is out-of-order in one of the files, so it's not getting added to the cluster before another resource that depends on it.  Could probably be fixed with a few minutes of trial-and-error.  Low priority obviously, since everything works if the user just re-runs the offending `kubectl apply`, which is probably the first thing everyone will try.

**Comment by joeholley** [comment]
Some output: 
```
unable to recognize "03-prometheus.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "03-prometheus.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
```
Some of this might just be that we need to let the cluster bring up the Prometheus Operator before trying to add `ServiceMonitor` or `Prometheus` resources.

**Comment by ihrankouski** [comment]
One way to prevent these error when installing Prometheus from separate JSON files is something like the following:
```
kubectl apply -f prometheus_operator.json
until kubectl get crd 2>/dev/null | grep -q prometheus ; do echo "." && sleep 1 ; done
kubectl apply -f prometheus.json
kubectl apply -f prometheus_service.json
kubectl apply -f metrics_servicemonitor.json
```

However this will not help in case of '03-prometheus.yaml'...

**Comment by jeremyje** [comment]
I have a helm chart now with Prometheus getting deployed and it works reliably. Basically instead of using prometheus-operator just using prometheus service discovery seems to work better. The configuration is just placed in a different configuration. Each pod basically specifies some annotations and prometheus will scrape them.

I can decouple this from helm and update the 03-prometheus.yaml a bit later if desired.

**Comment by jeremyje** [comment]
At this point I think we can call this done since we have a reasonable workaround with the helm chart.
There's also a pull request to make the Helm source of truth for canonical OM, 

https://github.com/GoogleCloudPlatform/open-match/pull/81
https://github.com/GoogleCloudPlatform/open-match/pull/119
